### ISSUE TITLE
Inconsistent Syntax Highlighting

### ISSUE THREAD

**Issue by heyvito** [tommasongr/nova-rails#13]
Hi there! Before anything, thank you so much for putting so much effort onto this extension! It's really helpful!

I found a few cases on syntax highlight either produces no highlighting, or produces inconsistent results. I'll attach a few different screenshots comparing Sublime's built-in Ruby syntax highlighter against Nova's:

<table>
<tr>
<td>Sublime Text</td>
<td>Nova</td>
</tr>
  <tr>
    <td><img width="1044" alt="image" src="https://user-images.githubusercontent.com/77198/161406235-537a826b-1899-402d-b291-8656805755dd.png"></td>
    <td><img width="1133" alt="image" src="https://user-images.githubusercontent.com/77198/161406248-e0b5809b-6d81-4a0f-a0dd-00a8faa9710d.png"></td>
</tr>
<tr>
<td><img width="962" alt="image" src="https://user-images.githubusercontent.com/77198/161406302-fc914a54-d3f7-4682-90af-7d15033834bc.png"></td>
<td><img width="1003" alt="image" src="https://user-images.githubusercontent.com/77198/161406320-23584246-c50e-4a4e-858e-d85018e8c00a.png">
</td>
<tr>
<td><img width="1005" alt="image" src="https://user-images.githubusercontent.com/77198/161406355-4647122b-53c1-4079-8c18-8b5dc66a6475.png"></td>
<td>
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/77198/161406367-fe24cee1-f6d9-49ca-a4db-66eafc8aacbb.png">
</td>
</tr>
<tr>
<td>Sublime Text</td>
<td>Nova</td>
</tr>
</table>

It seems it specially loses track when handling anything that's a method argument, multiline `%i` and `%W` statements, and chained method calls.
I'm pretty aware dealing with the syntax highlighting engine is not the easiest task, so please let me know in case I can assist in any way. I'll also try to fix that in my free time, and may come up with something, eventually.

Cheers!
— Vito

**Comment by heyvito** [comment]
Oh dear! Just figured out this extension does not provide syntax highlighting! I'm so sorry for my lack of attention, @tommasongr! I'll close this one. My bad. 🙈

**Comment by tommasongr** [comment]
@heyvito Hi there!

ahah don't worry. I'm happy to know that you're enjoying the extension 😆. If you have any other suggestion on how to improve it you're welcome to open new issues!

Enjoy

**Comment by eirvandelden** [comment]
@heyvito I get your confusion, where you perhaps looking for https://github.com/44brm/NovaRails/issues which is the Theme called "NovaRails"?
