### ISSUE TITLE
Autocomplete of "end" is driving me nuts

### ISSUE THREAD

**Issue by swillits** [tommasongr/nova-rails#24]
Something changed recently, and now whenever I type "end" it wants to autocomplete a do/end block for me. I'm just writing my code normally and this auto-suggestion keeps popping up and when I press return to go to the next line after "end", it's inserting a do block. As you can imagine, this is pretty maddening.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/821490/187518741-9d1f803e-4dd3-42c5-906c-c430ee9de7dd.png">

As far as I can tell, there's no control over this?

**Comment by tommasongr** [comment]
Hi @swillits 👋 sorry for the late reply but I was away for vacation and before that a bit busy with work. Thanks for pointing out this issue, I'll take a look asap.

**Comment by swillits** [comment]
Thanks!
