### ISSUE TITLE
Question: How do I make it so the extension detects Rails?

### ISSUE THREAD

**Issue by coderberry** [tommasongr/nova-rails#5]
<img width="235" alt="image" src="https://user-images.githubusercontent.com/12481/146426022-0b4862f1-50d2-48e6-808b-b6bbe519d894.png">

I don't know what I should expect in this panel. How can I get the content in the side panel to appear?

Thanks for all your hard work on this!!!!!!

**Comment by tommasongr** [comment]
Hi there! Thanks for the appreciation 😄

The information sidebar is just a wrapper around `rails about`. At least right now.

<img width="285" alt="CleanShot 2021-12-16 at 19 33 06@2x" src="https://user-images.githubusercontent.com/25225746/146428740-c76e66f1-5dec-42cc-b5f0-6d9ed1be0c9b.png">

---

As you can see below, I'm invoking the command in the root of the current Nova workspace. The `rails about` command works only if you are in a valid Rails root, so make sure that is the case.

```js
export async function aboutRails() {
    return new Promise((resolve, reject) => {
        const process = new Process('/usr/bin/env', {
            cwd: nova.workspace.path,
            args: ['rails', 'about'],
            stdio: ['ignore', 'pipe', 'ignore'],
            shell: true,
        })
        let str = ''
        let strings = []

        process.onStdout((output) => {
            str += output
        })

        process.onDidExit((status) => {
            // Split each line of the output in the strings array
            strings = str.match(/[^\r\n]+/g)

            if (
                status === 0 &&
                strings[0] == "About your application's environment"
            ) {
                resolve(strings)
            } else {
                reject(status)
            }
        })

        process.start()
    })
}
```

Another possibile issue is with the Rails version you are working with. Unfortunately I started using Rails just 6 months ago, so I'm not sure in which version the command was introduced. Do you see something like this If you run it in the terminal?

<img width="982" alt="CleanShot 2021-12-16 at 19 34 27@2x" src="https://user-images.githubusercontent.com/25225746/146429178-1650624d-71ae-4375-adb4-1c53bbcef2b2.png">

The last thing you can check is the Nova extension console. You can filter just the Ruby on Rails logs.

<img width="598" alt="CleanShot 2021-12-16 at 19 45 22@2x" src="https://user-images.githubusercontent.com/25225746/146430419-2350b2c4-ccbf-4885-8ee6-1155e27a7591.png">

Let me know if you find a solution 😉

**Comment by coderberry** [comment]
Thank you for your quick and thorough response. I wonder if the reason might be that I have a WARNING when I run `rails about`:

```shell
➜ rails about
SHRINE DEPRECATION WARNING: Using aws-sdk-s3 < 1.14 is deprecated and support for it will be removed in Shrine 3. Update to aws-sdk-s3 version 1.14 or higher
About your application's environment
Rails version             6.1.3.1
Ruby version              ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin20]
RubyGems version          3.0.3
Rack version              2.2.3
JavaScript Runtime        Node.js (V8)
Middleware                Webpacker::DevSe
```

I was able to confirm this was the reason by testing another Rails application.

**Comment by tommasongr** [comment]
You're welcome!
Yeah, unfortunately the sidebar does a line by line scraping and that WARNING messes up everything.

All in all, I hope you're enjoying your Nova experience so far and if you have any suggestion for the Rails extension let me know 😉
