### ISSUE TITLE
Syntax error in main.dist.js

### ISSUE THREAD

**Issue by kimili** [tommasongr/nova-rails#7]
I've noticed the ERB tag switcher stopped working. When I checked the extension console, I see this when the extension is activated:

```
Extension encountered an uncaught exception:
/Users/michael/Library/Application Support/Nova/Extensions/com.tommasonegri.Rails/Scripts/main.dist.js (Line 786)
SyntaxError: Unexpected private name #pin_or_unpin. Cannot parse class method with private name.
```

Seems like other functionality (such as open alternate file) is also broken as a result.

**Comment by tommasongr** [comment]
Hi there! I'm sorry for this 😕

It seems your javascript runtime has an error with private methods in classes (is a relative new syntax). I'm not sure why, maybe is a matter of your macOS version.

Right now is not really a problem for me to turn them into standard methods, so stand by for an update.

Anyway I wasn't aware of this compatibility issue, I'm sorry if it caused problems with your workflow.

**Comment by tommasongr** [comment]
Just pushed v3.2. It should fix the issue.

Let me know if it works now 😄

**Comment by kimili** [comment]
Thanks for the quick fix on this, @tommasongr, it's looking good over here with the new update! 🎉 

FWIW, I'm running MacOS Big Sur 11.6. Thanks again!
