### ISSUE TITLE
Honor both Gemfile as well as gems.rb

### ISSUE THREAD

**Issue by svoop** [tommasongr/nova-rails#8]
Bundler has introduced `gems.rb` as an alternative to `Gemfile` [back in 2017](https://depfu.com/blog/2017/09/06/gemfiles-new-clothes) (e.g. to have proper syntax coloring in editors).

Unfortunately, this extension only checks for `Gemfile`:

https://github.com/tommasongr/nova-rails/blob/c8a1f4c8b11db31bda48964e24dbe5dc120c4fea/src/Scripts/helpers.js#L42

How about adding support for `gems.rb` as well?

(I'm using Nova for months now and only found out today by pure coincidence that the Rails extension never really worked due to this.)

Thanks a bunch!

**Comment by tommasongr** [comment]
Hi there!

That's a great catch! I wasn't aware of this alternative naming convention, I'm sorry.

I just published an update (v3.3) that fixes the issue. Let me know if it works 😉

**Comment by svoop** [comment]
@tommasongr It most certainly does, thanks a bunch for the quick fix!
